theme: jekyll-theme-slate
title: ["Tiers-Lieux: comparing the way places define themselves and how they are talked about on Twitter"]
subtitle: ["Analysing tiers-lieux using Twitter and Commune Mesure"]
